mabger-meter/force-app/main/default/objects/Account/fields/Case_Contact_Email_to_Quote__c.field-meta.xml
<CustomField>
    <fullName>Case_Contact_Email_to_Quote__c</fullName>
    <label>Case Contact Email to Quote</label>
    <type>Email</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/Case_for_Quote__c.field-meta.xml
<CustomField>
    <fullName>Case_for_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field temporarily holds the ID of a case that needs to be associated with a quote, when creating a quote from a case. Please note that this field should not be used for any other purpose and that the value is only intended as being held temporarily. Do not use on a page layout, with the exception of testing purposes.</description>
    <inlineHelpText>This field temporarily holds the ID of a case that needs to be associated with a quote, when creating a quote from a case. Please note that this field should not be used for any other purpose and that the value is only intended as being held temporarily.</inlineHelpText>
    <label>Case for Quote</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/CaseNum_to_Quote__c.field-meta.xml
<CustomField>
    <fullName>CaseNum_to_Quote__c</fullName>
    <label>CaseNum to Quote</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/Company_Number__c.field-meta.xml
<CustomField>
    <fullName>Company_Number__c</fullName>
    <description>Represents the LX Company Number
10 - US
14 - Europe
28 - BM UK</description>
    <inlineHelpText>Represents the LX Company Number
10 - US
14 - Europe
28 - BM UK</inlineHelpText>
    <label>Company Number</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 - BADGER METER, INC. (US)</fullName>
            </value>
            <value>
                <fullName>14 - BADGER METER EUROPA GmbH (Germany)</fullName>
            </value>
            <value>
                <fullName>28 - BADGER METER UK, LTD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/PONum_to_Quote__c.field-meta.xml
<CustomField>
    <fullName>PONum_to_Quote__c</fullName>
    <label>PONum to Quote</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Case/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Case/recordTypes/Return.recordType-meta.xml
<RecordType>
    <fullName>Return</fullName>
    <active>true</active>
    <businessProcess>Service Process</businessProcess>
    <description>Used to initiate a Return case (Repair, Warranty Analysis, Return for Credit, or Customer Supplied Material).</description>
    <label>Return</label>
</RecordType>

mabger-meter/force-app/main/default/classes/NewQuoteCreateForCaseCntr.cls
/**
    @Name           :   NewQuoteCreateForCaseCntr
    @Created Date   :   08 Jan, 2021 by KKake
    @Description    :   An apex page controller for QuoteCreateForCase.page which will create a Quote on both Bigmachine and Salesforce.
    @TestClass      :   TestQuoteCreateForCaseCntr.cls
*/
public with sharing class NewQuoteCreateForCaseCntr {
  
    private Id                      caseId;
    private Id                      accountId;   
    private String                  strCaseNumber;
    public  String                  messages                {get; private set;}
    public  Boolean                 hasPONumber             {get; private set;} 

    public  Boolean                 hasExistingQuotes       {get; private set;}
    public  List <BigMachines__Quote__c> existingQuotes     {get; private set;}

    public String                   forwardingURL           {get; private set;}
      
    public  String                  companyNumber           {get; private set;}  
    public  String                  accountCurrency         {get; private set;}  
    
    public NewQuoteCreateForCaseCntr () {
        initialize();
        validate();
    }

      
    private void initialize () {
        caseId       = System.currentPageReference().getParameters().get('caseId');
        accountId    = System.currentPageReference().getParameters().get('accId');
        messages = '';
        forwardingURL = '';
        hasExistingQuotes = false;

        companyNumber = '';
        accountCurrency = '';
                       
        validate();
    }

 
    private void validate () {
        Case theCase = [Select Id, AccountId, PO_Number__c From Case Where Id = :caseId];
        Account account = [Select Company_Number__c, CurrencyIsoCode From Account Where Id = :accountId];
        
        companyNumber = account.Company_Number__c;
        accountCurrency = account.CurrencyIsoCode;
        
        hasPONumber = !String.isEmpty(theCase.PO_Number__c) && theCase.PO_Number__c != 'BADGER SERVICES';
        
        if (hasPONumber) getExistingQuotes(theCase.AccountId, theCase.PO_Number__c);

        System.debug('MESSAGES: '+ messages);
        System.debug('hasPONumber: '+ hasPONumber);        
        System.debug('Company Number: ' + companyNumber);
        System.debug('Account Currency: ' + accountCurrency);
    }

    public void continueOn () {
        System.debug('HAS EXISTING QUOTES: '+ hasExistingQuotes);
        
        if (accountCurrency != 'EUR' && companyNumber == '14 - BADGER METER EUROPA GmbH (Germany)')
        {                 
            return; 
         }
        else if(hasExistingQuotes == false)  
        {                                
                     
             createQuote();
         }
        
    }


    @TestVisible
    private void getExistingQuotes (String accountId, String poNumber) {
        existingQuotes = new List <BigMachines__Quote__c> ([Select Id, Name, CreatedDate, CreatedBy.Name, BigMachines__Status__c, BigMachines__Total_Amount__c From BigMachines__Quote__c Where BigMachines__Account__c = :accountId And PO_Number__c = :poNumber And CreatedDate = LAST_N_DAYS:30]);
        hasExistingQuotes = existingQuotes.size() > 0;
    }
  

    public PageReference createQuote () {
        
        // Get the case and it's account.
        Case c = [Select Id, AccountId, Account.Name, CaseNumber, PO_Number__c, ContactEmail From Case Where Id = :caseId];
        
        // Construct an update for the owning account that places this case ID in a particular field.
        Account a = new Account();
        a.Id = c.AccountId;
        a.Case_for_Quote__c = c.Id;
        a.CaseNum_to_Quote__c = c.CaseNumber;
        a.PONum_to_Quote__c   = c.PO_Number__c;
        a.Case_Contact_Email_to_Quote__c   = c.ContactEmail;
              
        update a;
        
        // Schedule a job that will remove the case id from the account in a few seconds.
        QuoteCreateForCaseSchedule.scheduleJob(a.Id, 30);
        
        // Now, return the URL for the quote creation so that navigation can continue onward.
        String host = System.URL.getSalesforceBaseUrl().getHost();
        //System.debug(host);
        host = host.replace('--c', '--bigmachines');
        //System.debug(host);
        //String baseURL = 'https://badgermeter--test--bigmachines.visualforce.com/';
        String accountName = EncodingUtil.urlEncode(c.Account.Name, 'UTF-8');
        forwardingURL = 'https://'+host+'/apex/QuoteCreate?CF00N50000002povU='+ accountName +'&CF00N50000002povU_lkid='+ c.AccountId +'&scontrolCaching=1&retURL=%2F'+ c.AccountId +'&sfdc.override=1';
        
        System.debug('Forwarding URL : '+ forwardingURL);
        
        return new PageReference(forwardingURL);
    }
  

    public PageReference returnToCase () {
        return new PageReference('/'+caseId);
    }

}