mabger-meter/force-app/main/default/objects/Account/fields/Case_Contact_Email_to_Quote__c.field-meta.xml
<CustomField>
    <fullName>Case_Contact_Email_to_Quote__c</fullName>
    <label>Case Contact Email to Quote</label>
    <type>Email</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/Case_for_Quote__c.field-meta.xml
<CustomField>
    <fullName>Case_for_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field temporarily holds the ID of a case that needs to be associated with a quote, when creating a quote from a case. Please note that this field should not be used for any other purpose and that the value is only intended as being held temporarily. Do not use on a page layout, with the exception of testing purposes.</description>
    <inlineHelpText>This field temporarily holds the ID of a case that needs to be associated with a quote, when creating a quote from a case. Please note that this field should not be used for any other purpose and that the value is only intended as being held temporarily.</inlineHelpText>
    <label>Case for Quote</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/CaseNum_to_Quote__c.field-meta.xml
<CustomField>
    <fullName>CaseNum_to_Quote__c</fullName>
    <label>CaseNum to Quote</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/PONum_to_Quote__c.field-meta.xml
<CustomField>
    <fullName>PONum_to_Quote__c</fullName>
    <label>PONum to Quote</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/classes/QuoteCreateForCaseSchedule.cls
global class QuoteCreateForCaseSchedule implements Schedulable {

    private Id     accountId;
    private String  thisJobName;
    
    
    public QuoteCreateForCaseSchedule (Id accountId, String jobName) {
        this.accountId     = accountId;
        this.thisJobName   = jobName;
    }
    
    public static void scheduleJob (Id accountId, Integer secondsFromNow) {
        
        DateTime now = DateTime.now().addSeconds(secondsFromNow);        
        String hour = String.valueOf(now.hour());
        String min = String.valueOf(now.minute()); 
        String ss = String.valueOf(now.second());

    //parse to cron expression
    String cronString = ss + ' ' + min + ' ' + hour + ' * * ?';
        
        String jobName = 'QuoteCreateForCaseSchedule-'+cronString;
        
        QuoteCreateForCaseSchedule job = new QuoteCreateForCaseSchedule(accountId, jobName);
        
        System.schedule(jobName, cronString, job);
    }
    
    
    global void execute (SchedulableContext sc) {
        Account a = [Select Id, Case_for_Quote__c, CaseNum_to_Quote__c, PONum_to_Quote__c, Case_Contact_Email_to_Quote__c From Account Where Id = :accountId];
        a.Case_for_Quote__c = null;
        a.CaseNum_to_Quote__c = null;
        a.PONum_to_Quote__c   = null;
        a.Case_Contact_Email_to_Quote__c   = null;
        update a;
        
    List <CronTrigger> thisJob = [SELECT Id FROM CronTrigger Where CronJobDetail.Name = :this.thisJobName Limit 1];
      System.debug('ABORT JOB ID: '+ this.thisJobName);
        System.abortJob(thisJob[0].Id);
    }
    
}