mabger-meter/force-app/main/default/objects/Account/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Customer Number</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/MATEST__c.field-meta.xml
<CustomField>
    <fullName>MATEST__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MATEST</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/National_Strategic_Account__c.field-meta.xml
<CustomField>
    <fullName>National_Strategic_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TMT Override</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <inlineHelpText>Select the company type</inlineHelpText>
    <label>Organization Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DC-Distributor Customer</fullName>
            </value>
            <value>
                <fullName>ED-Encompass Program Distributor</fullName>
            </value>
            <value>
                <fullName>FE-Flow End Customer</fullName>
            </value>
            <value>
                <fullName>FM-Skid Manufacturer/OEM</fullName>
            </value>
            <value>
                <fullName>HA-Flow House Account</fullName>
            </value>
            <value>
                <fullName>ID-International Distributor</fullName>
            </value>
            <value>
                <fullName>IR-Flow Industrial/Commercial Rep</fullName>
            </value>
            <value>
                <fullName>OD-Flow Open Distribution</fullName>
            </value>
            <value>
                <fullName>TD-Turf Distributor</fullName>
            </value>
            <value>
                <fullName>UC-Utility Customer</fullName>
            </value>
            <value>
                <fullName>UD-Utility Distributor</fullName>
            </value>
            <value>
                <fullName>UO-Utility Other</fullName>
            </value>
            <value>
                <fullName>WD-WYCO Distributor</fullName>
            </value>
            <value>
                <fullName>WE-WYCO End Customer/Contractor</fullName>
            </value>
            <value>
                <fullName>WM-WYCO OEM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/TMT_Search__c.field-meta.xml
<CustomField>
    <fullName>TMT_Search__c</fullName>
    <formula>CASE(UPPER(BillingCountry), 
&quot;UNITED STATES&quot;,&quot;USA-&quot; &amp;   LEFT(BillingPostalCode, 5) , 
&quot;CANADA&quot;, &quot;CAN-&quot; &amp; LEFT(BillingPostalCode, 3),
&quot;MEXICO&quot;, &quot;MEX-&quot; &amp;   UPPER(BillingState) , 
&quot;&quot;)</formula>
    <label>TMT Search</label>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>This is the template that will align with accounts do not use or sell Badger Meter products &amp; services, but rather partner with End Customers or Channel Partners (e.g. Billing Vendors, Engineering Firms, etc.)</description>
    <label>Other</label>
</RecordType>

mabger-meter/force-app/main/default/classes/Batch_TMTSync.cls
/*
	This batch syncs the Account and Account_Relationship__c objects with the TMT__c table nightly, or as scheduled.
	The MATest__c field is toggled and the record updated, which sends the record through its trigger + class logic.
	This can also be done ad hoc directly from the record detail view.
	Functionality of this batch can be extended to other objects by adding additional entries to the queryMap.

	Sample Execute Code
	
	ID batchProcessId = Database.executeBatch(new Batch_TMTSync());
	
	Sample Execute Anonymous Scheduling Code
	
	//Everyday @ 1:00 AM
	Batch_TMTSync.schedule('0 0 1 * * ?');
*/

public class Batch_TMTSync implements Database.Batchable<SObject>, Schedulable 
{
	final String baseAccountFilter = ' WHERE Organization_Type__c != null'
										+ ' AND TMT_Search__c != null'
										//+ ' AND Market__c != null'
										+ ' AND National_Strategic_Account__c = FALSE';
	final String baseAccountRelFilter = ' WHERE Market__c != null'
										+ ' AND TMT_Search__c != null'
										+ ' AND Partner_1__c != null'
										+ ' AND Partner_1__r.Customer_Number__c != null'		// 2019-10-08 - Allium IT, JWB - Added this clause to filter out account relationships where the owning account does not have a customer number.
										+ ' AND Manual_SC__c = FALSE'
										+ ' AND Partner_2_Shipping_Country__c in (\'UNITED STATES\', \'CANADA\', \'MEXICO\')';

	final Map<String, String> queryMap = new Map<String, String>{
		'ACCOUNT' => 'SELECT Id, MATest__c FROM Account' + baseAccountFilter,
		'ACCOUNT_RELATIONSHIP' => 'SELECT Id, MATest__c FROM Account_Relationship__c' + baseAccountRelFilter
	};

	public String objectName;
	
	public Batch_TMTSync(String objectName) 
	{
		this.objectName = objectName;
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC) 
	{
		return Database.getQueryLocator(queryMap.get(objectName));
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) 
   	{
		UUtil.inBatch = true;

		for (sObject sObj : scope) 
		{
			sObj.put('MATest__c', !(Boolean) sObj.get('MATest__c'));
		}

		update scope;
	}
	
	public void finish(Database.BatchableContext BC)
    {
    	//nothing to do
    }

    public void execute(SchedulableContext SC) 
    {
        Id accountBatchId = Database.executeBatch(new Batch_TMTSync('ACCOUNT'));
        Id accountRelationshipBatchId = Database.executeBatch(new Batch_TMTSync('ACCOUNT_RELATIONSHIP'));
    }
    
    public static void schedule()
    {
        schedule(null);
    }
    
    public static void schedule(string jobSchedule)
    {
        if (jobSchedule == null || jobSchedule.trim().length() == 0)
        {
            jobSchedule = '0 0 1 * * ?'; //Run the class at 1:00 AM
        }
        
        System.schedule(
        		(Test.isRunningTest()) ? 'Batch_TMTSync Account Processing TESTING' : 'Batch_TMTSync Account Processing', 
        		jobSchedule, 
        		new Batch_TMTSync('ACCOUNT')
        	);

        System.schedule(
        		(Test.isRunningTest()) ? 'Batch_TMTSync Account Relationship Processing TESTING' : 'Batch_TMTSync Account Relationship Processing', 
        		jobSchedule, 
        		new Batch_TMTSync('ACCOUNT_RELATIONSHIP')
        	);
    }
	
}