mabger-meter/force-app/main/default/objects/Account/fields/Flow_Process_Valve__c.field-meta.xml
<CustomField>
    <fullName>Flow_Process_Valve__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow - Process/Valve</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/Flow_RA_Distributor__c.field-meta.xml
<CustomField>
    <fullName>Flow_RA_Distributor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow - RA Distributor</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/Flow_Test_Measure__c.field-meta.xml
<CustomField>
    <fullName>Flow_Test_Measure__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow - Test &amp; Measure</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Account/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <inlineHelpText>Select the company type</inlineHelpText>
    <label>Organization Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DC-Distributor Customer</fullName>
            </value>
            <value>
                <fullName>ED-Encompass Program Distributor</fullName>
            </value>
            <value>
                <fullName>FE-Flow End Customer</fullName>
            </value>
            <value>
                <fullName>FM-Skid Manufacturer/OEM</fullName>
            </value>
            <value>
                <fullName>HA-Flow House Account</fullName>
            </value>
            <value>
                <fullName>ID-International Distributor</fullName>
            </value>
            <value>
                <fullName>IR-Flow Industrial/Commercial Rep</fullName>
            </value>
            <value>
                <fullName>OD-Flow Open Distribution</fullName>
            </value>
            <value>
                <fullName>TD-Turf Distributor</fullName>
            </value>
            <value>
                <fullName>UC-Utility Customer</fullName>
            </value>
            <value>
                <fullName>UD-Utility Distributor</fullName>
            </value>
            <value>
                <fullName>UO-Utility Other</fullName>
            </value>
            <value>
                <fullName>WD-WYCO Distributor</fullName>
            </value>
            <value>
                <fullName>WE-WYCO End Customer/Contractor</fullName>
            </value>
            <value>
                <fullName>WM-WYCO OEM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Flow_Concrete_Finishing__c.field-meta.xml
<CustomField>
    <fullName>Flow_Concrete_Finishing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow - Concrete Finishing</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Lifecycle_Status__c</fullName>
    <label>Lifecycle Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Utility__c.field-meta.xml
<CustomField>
    <fullName>Utility__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Utility</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/classes/TestContactUpdate.cls
@isTest
private class TestContactUpdate{

    static testMethod void Contact_MQL_Update(){    
              
        Account acc = new Account(
            Name = 'testaccount',
            Organization_Type__c = 'UC - Utility Customer'             
        );
        insert acc;

        Id p = [SELECT id FROM Profile WHERE Name='2017 Badger Meter Partner Community User'].id;
                    
        Contact con = new Contact(
            AccountId = acc.id,
            Lastname = 'testcontact',
            Firstname ='testdata1',
            Email='test123@noemail.com',
            OwnerId = Userinfo.getUserid(),
            Lifecycle_Status__c = '02 - MCL'
            );
        insert con;  
                  
        User user = new User(
            Alias = 'badger12',
            Email='badgermetertest123@noemail.com',
            Emailencodingkey='UTF-8',
            Lastname='Testing',
            Languagelocalekey='en_US',
            Localesidkey='en_US',
            Profileid = p, 
            Country='United States',
            IsActive =true,
            ContactId = con.Id,
            Timezonesidkey='America/Los_Angeles', 
            Username='badgermetertest123@noemail.com');
       
        insert user;
        system.runAs(user) {
            // statements to be executed by this test user.
        }

        con.Lifecycle_Status__c='03 - MQL';
        con.Flow_Concrete_Finishing__c=TRUE;
        con.Flow_Process_Valve__c=TRUE;
        con.Flow_RA_Distributor__c=TRUE;
        con.Flow_Test_Measure__c=TRUE;
        con.Utility__c=TRUE;
              
        Test.startTest();
        update con;
        Test.stopTest();

        //Requery the contact record and check to make sure it was updated.
        Contact result = 
            [Select
               Lifecycle_status__c,Flow_Concrete_Finishing__c,Flow_Process_Valve__c,Flow_RA_Distributor__c,Flow_Test_Measure__c,Utility__c
            From
                Contact
            ];

        System.assertEquals(
        con.Lifecycle_Status__c,result.Lifecycle_Status__c);    
    }
}