mabger-meter/force-app/main/default/objects/Account/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>List of Products used to control access to Product specific areas of Extranet</description>
    <inlineHelpText>List of Products used to control access to Product specific areas of Extranet</inlineHelpText>
    <label>Extranet Product Groups</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&quot;AquaCUE&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Automotive Oval Gear&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Concrete&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Coriolis&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Cox&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Dynasonics&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Flow Dynamics&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Impeller/Data Industrial&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Industrial MKE M.M.&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;ModMAG M Series&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;NMAAI Only&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Preso&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Research Control Valves (RCV)&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Sales Policies&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Utility&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Utility - Latin America&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Utility Sub-Distributors&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Vortex&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Wyco&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Wyco - Latin America&quot;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <description>this will capture the domain portion of a users email address.  This is used to match new contacts created via community self registration to their correct accounts.</description>
    <formula>RIGHT(Email, len(Email) - FIND(&quot;@&quot;, Email, 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>this will capture the domain portion of a users email address.  This is used to match new contacts created via community self registration to their correct accounts.</inlineHelpText>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Domain_Match_Found__c.field-meta.xml
<CustomField>
    <fullName>Domain_Match_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this field indicates a domain match was found when the contact self registered for access to the community / extranet.</description>
    <inlineHelpText>this field indicates a domain match was found when the contact self registered for access to the community / extranet.</inlineHelpText>
    <label>Domain Match Found</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/No_Matching_Domain__c.field-meta.xml
<CustomField>
    <fullName>No_Matching_Domain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates that no match was found for the contact&apos;s email domain when they self-registered for access to the extranet.  When checked, this field will send out a rejection notice to the contact.  This field should not be checked manually.  It&apos;s only checked by automation when a user / contact self-registers for access to the extranet.</description>
    <inlineHelpText>This field indicates that no match was found for the contact&apos;s email domain when they self-registered for access to the extranet.  When checked, this field will send out a rejection notice to the contact.  This field should not be checked manually.</inlineHelpText>
    <label>No Matching Domain</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Pricebook_Location__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Location__c</fullName>
    <description>This Field is used to designate User Location and what Pricebooks the User should have access to.</description>
    <label>Pricebook Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&quot;United States&quot;</fullName>
                <default>true</default>
                <label>&quot;United States&quot;</label>
            </value>
            <value>
                <fullName>&quot;Latin America&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Badger Meter Internal&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Badger Meter Internal Advanced&quot;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Pricebook_Location_for_Extranet__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Location_for_Extranet__c</fullName>
    <description>Store location data for Extranet</description>
    <label>Pricebook Location for Extranet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Products_CSV_for_Extranet_1__c.field-meta.xml
<CustomField>
    <fullName>Products_CSV_for_Extranet_1__c</fullName>
    <description>In general, do not manually edit! (Contains list of products. Quoted and Comma-Separated-Values. E.g. &quot;ABC&quot;, &quot;EFG, &quot;XYZ&quot;. Updated via triggers on Account, Contact. Used by User formula field Assertion_Data_For_Extranet__c.)</description>
    <inlineHelpText>In general, do not manually edit! (Contains list of products. Quoted and Comma-Separated-Values. E.g. &quot;ABC&quot;, &quot;EFG, &quot;XYZ&quot;. Updated via triggers on Account, Contact. Used by User formula field Assertion_Data_For_Extranet__c.)</inlineHelpText>
    <label>Products CSV for Extranet 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Products_CSV_for_Extranet_2__c.field-meta.xml
<CustomField>
    <fullName>Products_CSV_for_Extranet_2__c</fullName>
    <description>In general, do not manually edit! (Contains list of products. Quoted and Comma-Separated-Values. E.g. &quot;ABC&quot;, &quot;EFG, &quot;XYZ&quot;. Updated via triggers on Account, Contact. Used by User formula field Assertion_Data_For_Extranet__c.)</description>
    <inlineHelpText>In general, do not manually edit! (Contains list of products. Quoted and Comma-Separated-Values. E.g. &quot;ABC&quot;, &quot;EFG, &quot;XYZ&quot;. Updated via triggers on Account, Contact. Used by User formula field Assertion_Data_For_Extranet__c.)</inlineHelpText>
    <label>Products CSV for Extranet 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Products_CSV_for_Extranet_3__c.field-meta.xml
<CustomField>
    <fullName>Products_CSV_for_Extranet_3__c</fullName>
    <description>In general, do not manually edit! (Contains list of products. Quoted and Comma-Separated-Values. E.g. &quot;ABC&quot;, &quot;EFG, &quot;XYZ&quot;. Updated via triggers on Account, Contact. Used by User formula field Assertion_Data_For_Extranet__c.)</description>
    <inlineHelpText>In general, do not manually edit! (Contains list of products. Quoted and Comma-Separated-Values. E.g. &quot;ABC&quot;, &quot;EFG, &quot;XYZ&quot;. Updated via triggers on Account, Contact. Used by User formula field Assertion_Data_For_Extranet__c.)</inlineHelpText>
    <label>Products CSV for Extranet 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Products_CSV_for_Extranet_4__c.field-meta.xml
<CustomField>
    <fullName>Products_CSV_for_Extranet_4__c</fullName>
    <description>In general, do not manually edit! (Contains list of products. Quoted and Comma-Separated-Values. E.g. &quot;ABC&quot;, &quot;EFG, &quot;XYZ&quot;. Updated via triggers on Account, Contact. Used by User formula field Assertion_Data_For_Extranet__c.)</description>
    <inlineHelpText>In general, do not manually edit! (Contains list of products. Quoted and Comma-Separated-Values. E.g. &quot;ABC&quot;, &quot;EFG, &quot;XYZ&quot;. Updated via triggers on Account, Contact. Used by User formula field Assertion_Data_For_Extranet__c.)</inlineHelpText>
    <label>Products CSV for Extranet 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Products_for_Extranet__c.field-meta.xml
<CustomField>
    <fullName>Products_for_Extranet__c</fullName>
    <description>This Field is used to display what Products the Contact should have access to in the Extranet.  The data is controlled by Accounts.Products__c.</description>
    <label>Products for Extranet</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

mabger-meter/force-app/main/default/objects/User/fields/Deactivate_User__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate User</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/classes/UContact.cls
/* 
    Created By:  GearsCRM
    Created Date: 9/15/2015
    Description:  contact Helper Class
    
    Modified By   :  Trekbin
    Modified Date :  14 Oct, 2015
    Description   :  Modified linkDomainAccount method to deactivate the User.
	Test class    :  test_UContact 
*/
  
public without sharing class UContact    
{

    /**
     * updatePricebookLocation Sets Contact.Pricebook_Location_for_Extranet__c
     * @param  record List of Contact records
     * @param  oldMap Trigger.oldMap
     */
    public static void updatePricebookLocation(List <contact> records, map<id,contact> oldMap)
    {  
        boolean isInsert = (oldMap == null);
        
        for(contact con : records)
        {
            string retvalue = '';
            if (isInsert == true || (isInsert == false && con.Pricebook_Location__c  != oldMap.get(con.id).Pricebook_Location__c ))
            {
                if(con.Pricebook_Location__c != null)
                {
                    retvalue = con.Pricebook_Location__c;
                    retvalue = retvalue.replaceAll(';',',');
                    con.Pricebook_Location_for_Extranet__c = retvalue;
                   //con.Pricebook_Location_for_Extranet__c = con.Pricebook_Location__c;
                }
                else if(con.Pricebook_Location__c  == null)
                {
                    con.Pricebook_Location_for_Extranet__c = '';
                }
            }   
        }
    }
    
    /**
     * updateProductDetails UAccount.updateProductDetails should use this method -- duplicate logic
     * @param  record List of Contact records
     * @param  oldMap Trigger.oldMap
     */
    public static void updateProductDetails(List <contact> records, map<id,contact> oldMap)
    {  
        boolean isInsert = (oldMap == null);
        list<contact> updContact = new list<contact>();   
        for(contact con : [select id,AccountId,account.products__c,Products_CSV_for_Extranet_1__c,Products_CSV_for_Extranet_2__c,Products_CSV_for_Extranet_3__c,Products_CSV_for_Extranet_4__c,Inactive__c   
                         from contact where id in : records and account.products__c != null])
                        // from contact where id in : records ])
        {
            string returnvalue = '';
            //if (isInsert == true || (isInsert == false && con.AccountId  != oldMap.get(con.id).AccountId && (con.account.products__c != null || con.account.products__c == null )))
            
            system.debug('_____isInsert_____' + isInsert);
            system.debug('_____con.Inactive__c____' + con.Inactive__c);
            system.debug('_____con.AccountId____' + con.AccountId);
            if(isInsert == false)
            {
                system.debug('_____oldMap.get(con.id).AccountId____' + oldMap.get(con.id).AccountId);
                system.debug('_____oldMap.get(con.id).Inactive__c____' + oldMap.get(con.id).Inactive__c);
            }
            
            if ((isInsert == true && con.Inactive__c == false) 
               || (isInsert == false
                  &&((con.AccountId  != oldMap.get(con.id).AccountId &&  con.Inactive__c == false) || (con.Inactive__c != oldMap.get(con.id).Inactive__c && con.Inactive__c == false))))
            {
                system.debug('______con.account.products__c____' + con.account.products__c);
                if(con.account.products__c != null)
                {
                    returnvalue = con.account.products__c;
                    returnValue=returnValue.replaceAll(';',',');
                    con.Products_for_Extranet__c = returnValue;
               
                    con.Products_CSV_for_Extranet_1__c = con.Products_for_Extranet__c.MID(0,254);
                    con.Products_CSV_for_Extranet_2__c = con.Products_for_Extranet__c.MID(255,255);
                    con.Products_CSV_for_Extranet_3__c = con.Products_for_Extranet__c.MID(510,255);
                    con.Products_CSV_for_Extranet_4__c = con.Products_for_Extranet__c.MID(765,255);
                }
                else if(con.account.products__c == null)
                {
                    con.Products_for_Extranet__c = '';
                    con.Products_CSV_for_Extranet_1__c = '';
                    con.Products_CSV_for_Extranet_2__c = '';
                    con.Products_CSV_for_Extranet_3__c = '';
                    con.Products_CSV_for_Extranet_4__c = '';
                }
                system.debug('______con.Products_CSV_for_Extranet_1__c______' + con.Products_CSV_for_Extranet_1__c);
                system.debug('______con.Products_CSV_for_Extranet_2__c______' + con.Products_CSV_for_Extranet_2__c);
                updContact.add(con);
            }   
        }
        
        if(updContact.size() > 0 && updContact != null)
        {
            update updContact;
        }
    }
    
    // 2018-10-17 - Allium IT - Removed by Joe Bunda per client request
    /*
    public static void linkDomainAccount(List <contact> records) { 	
    	
    	//Modified by Trekbin on 14 Oct, 2015.
    	map<string,Domain__c> domainMap = new map<string,Domain__c>();
		set<Id> setNoMatchingDomainContactIds = new set<Id>();
		List<Contact> lstContactsToUpdate = new List<Contact>();
		
        for(Domain__c dm :[	SELECT id,Account_Name__c,Domain_Name__c 
        					FROM domain__c 
        					WHERE Domain_Name__c != null
        				  ]) {
        	
            domainMap.put(dm.Domain_Name__c,dm);
        }
           
        for(contact con : records) {
        	
            AccountCustomSettings__c acs = AccountCustomSettings__c.getOrgDefaults();
      		
            if (con.accountId != null && con.accountId == acs.Self_Registration_Account_ID__c && domainMap.containsKey(con.Domain__c)) {
            	
                if(domainMap.containskey(con.Domain__c) && domainMap.get(con.Domain__c).Account_Name__c == null) {
                	
                    Contact objContact = new Contact(Id = con.Id, No_Matching_Domain__c = true);
                    lstContactsToUpdate.add(objContact);
                    setNoMatchingDomainContactIds.add(objContact.Id);
                
                } else if(domainMap.containskey(con.Domain__c) && domainMap.get(con.Domain__c).Account_Name__c != null) {
                	
                    Contact objContact = new Contact(Id = con.Id, accountId = domainMap.get(con.Domain__c).Account_Name__c, Domain_Match_Found__c = true);
                    lstContactsToUpdate.add(objContact);
                }
                
            } else {
            	
                Contact objContact = new Contact(Id = con.Id, No_Matching_Domain__c = true);
                lstContactsToUpdate.add(objContact);
                setNoMatchingDomainContactIds.add(objContact.Id);
            }
        }
        
        if(!lstContactsToUpdate.isEmpty())
        	update lstContactsToUpdate;
        	
        deactivateUser(setNoMatchingDomainContactIds);
    }
    
    @future
    public static void deactivateUser(set<Id> setNoMatchingDomainContactIds) {
    	
    	List<User> lstUsersToDisable = new List<User>();
    	
    	for(User objUser :  [	SELECT Isactive, IsPortalEnabled, Deactivate_User__c
        						FROM User 
        						WHERE ContactID IN:setNoMatchingDomainContactIds 
        						AND Isactive = true
        					]) {

        	objUser.Isactive = false;
        	objUser.Deactivate_User__c = true;
        	lstUsersToDisable.add(objUser);
        }

		if(!lstUsersToDisable.isEmpty()) { 
			
			try { 
				
				update lstUsersToDisable;
				
			} catch(exception e) {
				
				system.debug('--------message--------' + e.getMessage());
			}
			
		}	
    }
	*/
}