mabger-meter/force-app/main/default/objects/Account/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>List of Products used to control access to Product specific areas of Extranet</description>
    <inlineHelpText>List of Products used to control access to Product specific areas of Extranet</inlineHelpText>
    <label>Extranet Product Groups</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&quot;AquaCUE&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Automotive Oval Gear&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Concrete&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Coriolis&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Cox&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Dynasonics&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Flow Dynamics&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Impeller/Data Industrial&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Industrial MKE M.M.&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;ModMAG M Series&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;NMAAI Only&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Preso&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Research Control Valves (RCV)&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Sales Policies&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Utility&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Utility - Latin America&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Utility Sub-Distributors&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Vortex&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Wyco&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Wyco - Latin America&quot;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <description>this will capture the domain portion of a users email address.  This is used to match new contacts created via community self registration to their correct accounts.</description>
    <formula>RIGHT(Email, len(Email) - FIND(&quot;@&quot;, Email, 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>this will capture the domain portion of a users email address.  This is used to match new contacts created via community self registration to their correct accounts.</inlineHelpText>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Contact/fields/Pricebook_Location__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Location__c</fullName>
    <description>This Field is used to designate User Location and what Pricebooks the User should have access to.</description>
    <label>Pricebook Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&quot;United States&quot;</fullName>
                <default>true</default>
                <label>&quot;United States&quot;</label>
            </value>
            <value>
                <fullName>&quot;Latin America&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Badger Meter Internal&quot;</fullName>
            </value>
            <value>
                <fullName>&quot;Badger Meter Internal Advanced&quot;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/User/fields/Deactivate_User__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate User</label>
    <type>Checkbox</type>
</CustomField>

mabger-meter/force-app/main/default/classes/test_UContact.cls
@isTest(SeeAllData=true)
public class test_UContact {
 
    public static testMethod void ContactMeth()
    {
        //cretae Account
        Account acc1 = new Account();
        acc1.Type = 'End User - 1';
        acc1.Name = 'Test Acc1';
        acc1.products__c = 'test product';
		acc1.BillingCountryCode = 'US';
		acc1.BillingPostalCode = '68137';
        insert acc1;
        
        //Create Contact..
        Contact con = new Contact();
        con.LastName= 'TestCon';
        con.AccountId = acc1.Id;
        con.Pricebook_Location__c = 'Latin America';
        insert con ;
        
        system.debug('_______con_____' + con);

        con.Pricebook_Location__c = 'United States';
        update con;

        system.debug('_______con2____' + con);
       

  }
    
	// 2018-10-17 - Allium IT - Removed by Joe Bunda per client request
    /*
    static testMethod void testLinkDomainAccount() {
        
        //cretae Account
        Account acc1 = new Account();
        acc1.Type = 'End User - 1';
        acc1.Name = 'Test Acc1';
        acc1.products__c = 'test product';
		acc1.BillingCountryCode = 'US';
		acc1.BillingPostalCode = '68137';
        insert acc1;
        
        AccountCustomSettings__c acs = AccountCustomSettings__c.getOrgDefaults();
        
        Domain__c dm = new Domain__c(Account_Name__c = acc1.Id, Domain_Name__c = 'trigger.com');
        insert dm;
        
        //Create a contact
        contact c = new contact(accountid=acs.Self_Registration_Account_ID__c, firstname='test', lastname='test', Email = 'testDeactiv@trigger.com');
        insert c;
        
    }
    
    static testMethod void testdeactivateUser() {
        
        //cretae Account
        Account acc1 = new Account();
        acc1.Type = 'End User - 1';
        acc1.Name = 'Test Acc1';
        acc1.products__c = 'test product';
		acc1.BillingPostalCode = '68137';
		acc1.BillingCountryCode = 'US';
        insert acc1;
        
        Domain__c dm = new Domain__c(Account_Name__c = acc1.Id, Domain_Name__c = 'trigger.com');
        insert dm;
        
        //Create a contact
        Contact c = new Contact(accountid=acc1.id, firstname='test', lastname='test', Email = 'testDeactiv@trigger.com');
        insert c;
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User']; 
        
        User u = new User();
        u.Alias = 'deact';
        u.Email = 'testDeactiv@trigger.com';
        u.EmailEncodingKey = 'UTF-8';
        u.Firstname = 'Test';
        u.Lastname = 'User';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.Profileid = p.Id;
        u.TimezoneSidKey = 'America/Los_Angeles';
        u.Username = 'testDeactiv@trigger.com';
        u.isActive = true;
        u.ContactId = c.Id;
        
        insert u;
        
        Set<Id> setContactIds = new Set<Id>{c.id};
        Test.startTest();
            UContact.deactivateUser(setContactIds);
        Test.stopTest();
    }
    */
    
    static testMethod void testBatchDisableCommunityUser() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator']; 
        
        User u = new User();
        u.Alias = 'deact';
        u.Email = 'testDeactiv1@trigger.com';
        u.EmailEncodingKey = 'UTF-8';
        u.Firstname = 'Test';
        u.Lastname = 'User';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.Profileid = p.Id;
        u.TimezoneSidKey = 'America/Los_Angeles';
        u.Username = 'testDeactiv1@trigger.com';
        u.isActive = true;
        u.Deactivate_User__c = true;
        insert u;
        
        Database.executebatch(new BatchDisableCommunityUser());
    }
    
    //static testMethod void testScheduleBatchDisableCommunityUser() {
    //    
    //    ScheduleBatchDisableCommunityUser.scheduleBatch();
   // }
}