mabger-meter/force-app/main/default/objects/Case/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/Case/recordTypes/Inquiry.recordType-meta.xml
<RecordType>
    <fullName>Inquiry</fullName>
    <active>true</active>
    <businessProcess>Inquiry Process</businessProcess>
    <description>Most basic case format, default record type.</description>
    <label>Inquiry</label>
</RecordType>

mabger-meter/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <description>This object enables the case object to add a number of products to a case for return or warranty analysis.</description>
    <label>Product Line</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mabger-meter/force-app/main/default/objects/Product_Line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Product_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Use the Description field when you can&apos;t identify a product via the Item Number field above. This field allows you to populate a freeform description to help identify the product the customer is returning.</inlineHelpText>
    <label>Freeform Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mabger-meter/force-app/main/default/objects/Product_Line__c/fields/Sample_Size__c.field-meta.xml
<CustomField>
    <fullName>Sample_Size__c</fullName>
    <description>Indicates the sample size of units that should be automated created for the product line.</description>
    <inlineHelpText>Indicates the sample size of units that should be automated created for the product line.</inlineHelpText>
    <label>Sample Size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mabger-meter/force-app/main/default/classes/UProductLine_Test.cls
@isTest(seealldata = true) 
private class UProductLine_Test
{
    static testMethod void Test1()
    {
       id caseRecordTypeId = Sobjecttype.case.getRecordTypeInfosByName().get('Invoice Inquiry').getRecordTypeId();
        
        //cretae Account  
        Account acc1 = new Account();
        acc1.Type = 'End User - 1';
        acc1.Name = 'Test Acc1';
		acc1.BillingCountryCode = 'US';
		acc1.BillingPostalCode = '68137';
        insert acc1;
        
        Case c = new Case();
        c.subject = 'test123';
        c.status = 'open';
        c.AccountId = acc1.id;
        insert c;
       
        Product_Line__c pl = new Product_Line__c();
        pl.Case__c = c.id;
        pl.Sample_Size__c = 2;
        pl.Description__c = 'Test product line';
        insert pl;
        
        pl.sample_size__c = 3;
        update pl;
    }
}