mabger-meter/force-app/main/default/objects/Case/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

mabger-meter/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <description>This object enables the case object to add a number of products to a case for return or warranty analysis.</description>
    <label>Product Line</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mabger-meter/force-app/main/default/objects/Product_Line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mabger-meter/force-app/main/default/classes/UProductUnitTest.cls
@IsTest
public class UProductUnitTest {
	
    @TestSetup
    public static void createTestData () {
        Account testAccount = new Account(Name='Test Account');
        insert testAccount;
        
        Case testCase = new Case(AccountId=testAccount.Id, Subject='Test Case', Status='Open');
        insert testCase;
        
        Product_Line__c testProductLine = new Product_Line__c(Case__c=testCase.Id);
        insert testProductLine;
        
        List <Product_Units__c> testProductUnits = new List <Product_Units__c> ();
        for (Integer i = 0; i < 400; i++) {
            testProductUnits.add(new Product_Units__c(Case__c=testCase.Id, Product_Line__c=testProductLine.Id));
        }
        insert testProductUnits;
    }
    
    
    public static testmethod void test () {
        Product_Units__c testProductUnit = [Select Id, Product_Line__c From Product_Units__c Limit 1];
        Integer productUnitCount = (Integer) [Select Product_Line__c, Count(Id) ProductUnitCount From Product_Units__c Where Product_Line__c = :testProductUnit.Product_Line__c Group By Product_Line__c Limit 1][0].get('ProductUnitCount');
        System.debug(productUnitCount);
        
        Test.startTest();
        update testProductUnit;
        Test.stopTest();
        
		testProductUnit = [Select Id, Product_Line__c, ProductUnitLineNumber__c From Product_Units__c Where Id = :testProductUnit.Id];
		System.debug(testProductUnit.ProductUnitLineNumber__c);  
        
        // Ensure that the code assigned the next product unit line number.
        System.assertEquals(productUnitCount+1, testProductUnit.ProductUnitLineNumber__c);
    }
    
}